apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: adminer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: adminer
    spec:
      containers:
        - image: adminer
          name: adminer
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: adminer
  name: adminer
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: adminer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: adminer-ingress
  namespace: postgres
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: rsocket.local
      http:
        paths:
          - backend:
              serviceName: adminer
              servicePort: 8080
            path: /