apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  namespace: activemq
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - image: cithub/activemq
          name: activemq
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 1000Mi
              cpu: 400m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: activemq
  name: activemq
  namespace: activemq
spec:
  ports:
    - name: dashboard
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: jms
      port: 61616
      protocol: TCP
      targetPort: 61616
  selector:
    app: activemq
  sessionAffinity: None
  type: ClusterIP