apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
        - name: server
          image: backend-app:v1
          imagePullPolicy: Never
          env:
            - name: AMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: amq_url
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_host
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_user
            - name: PG_PSWD
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_pswd
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_db
          ports:
            - containerPort: 8081
              name: svc-port
              protocol: TCP