apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - name: backend
          image: backend-app:v1
          env:
            - name: AMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: camel.activemq.broker-url
          ports:
            - containerPort: 8081
              name: svc-port
              protocol: TCP
