apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: backend-app:v1
          imagePullPolicy: Never
          env:
            - name: AMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: amq_url
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_host
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_user
            - name: PG_PSWD
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_pswd
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: local-config
                  key: pg_db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: server
spec:
  ports:
    - name: rsocket
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: management
      port: 8484
      protocol: TCP
      targetPort: 8484
  selector:
    app: server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  namespace: server
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: rsocket.local
      http:
        paths:
          - backend:
              serviceName: server
              servicePort: 7000
            path: /