server:
  port: 8421

app:
  in-topic: in_topic
  out-topic: out_topic
  table-name: messages
  jms-ttl-millis: 5000

postgres:
  server: localhost
  port: 5432
  user: postgres
  pswd: camel
  db: postgres

spring:
  rsocket:
    server:
      port: 7000
      transport: tcp
      address: 0.0.0.0
      mapping-path:

camel:
  springboot:
    name: "reactive"
  component:
    reactive-streams:
      thread-pool-max-size: 5
    activemq:
      broker-url: "tcp://localhost:61616"
      connection-factory: CachingConnectionFactory

#    jms:
#      transacted: true
#      acknowledgement-mode-name: "SESSION_TRANSACTED"
#      lazy-create-transaction-manager: false

management:
  server:
    port: 8484
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  level:
    root: info
    biz.cit.reactive: info
