server:
  port: 8421

app:
  in-topic: in_topic
  out-topic: out_topic
  table-name: messages

postgres:
  server: localhost
  port: 5432
  user: postgres
  pswd: camel
  db: postgres

spring:
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: false
      max-connections: 100
  rsocket:
    server:
      port: 7000
      transport: tcp
      address: 0.0.0.0

camel:
  springboot:
    name: "reactive"

management:
  server:
    port: 8484
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  level:
    root: info
    biz.cit.reactive: info
