server:
  port: 8421

app:
  in-queue: jms:inqueue
  out-queue: jms:outqueue



spring:
  activemq:
    broker-url: tcp://localhost:61616

    pool:
      enabled: false
      max-connections: 100
  rsocket:
    server:
      address: localhost
      transport: tcp
      mapping-path: /reactive

camel:
  springboot:
    name: "reactive"

management:
  server:
    port: 8484
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

