server:
  port: 8421
local:
  rsocket:
    server:
      port: 8422
app:
  in-queue: jms:inqueue
  out-queue: jms:outqueue

postgres:
  server: localhost
  port: 5432
  user: postgres
  pswd: camel
  db: postgres

spring:
  activemq:
    broker-url: tcp://localhost:61616

    pool:
      enabled: false
      max-connections: 100
  rsocket:
    server:
      port: 7000
      address: localhost
      transport: tcp
      mapping-path: /reactive

camel:
  springboot:
    name: "reactive"

management:
  server:
    port: 8484
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

