version: '3.7'
services:

  activemq:
    image: cithub/activemq
    hostname: activemq
    container_name: activemq
    restart: always
    ports:
      - 61616:61616
      - 5672:5672
      - 61613:61613
      - 1883:1883
      - 61614:61614
      - 8161:8161
    networks:
      - camel

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: camel
    ports:
      - 5432:5432
    networks:
      - camel

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - camel

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    command: --serviceExecutor adaptive
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - camel

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - camel

networks:
  camel: